version: "3.8"
services:
  backend:
    image: "modefair/springboot-react-fullstack:4.7.2021.19.57.27"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev